// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/9/2026, 10:19:52 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/thebault/projects/generationwestdance.fr/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/generationwestdance.fr/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/generationwestdance.fr/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/generationwestdance.fr/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/generationwestdance.fr/src/plugins/**/*.{js,ts,mjs}","/home/thebault/projects/generationwestdance.fr/src/composables/**/*.{js,ts,mjs}","/home/thebault/projects/generationwestdance.fr/src/utils/**/*.{js,ts,mjs}","/home/thebault/projects/generationwestdance.fr/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/generationwestdance.fr/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/generationwestdance.fr/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/thebault/projects/generationwestdance.fr/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;